### ISSUE TITLE
With Version 2.12.31: PlugIns are now only in "sandbox" mode registred

### ISSUE THREAD

**Issue by AlGu1** [phuocle/Dynamics-Crm-DevKit#39]
Hi,
your changes in Task.cs File:
From:
                case "plugins":
                    var plugin = new TaskPlugin(crmServiceClient, currentDirectory, arguments);
                    plugin.Run();
                    break;

To:
                //case "plugins":
                //    var plugin = new TaskPlugin(crmServiceClient, currentDirectory, arguments);
                //    plugin.Run();
                //    break;
...
                case "plugins":
                case "workflows":
                case "dataproviders":
                    var server = new TaskServer(crmServiceClient, currentDirectory, arguments);
                    server.Run();
                    break;

have the effect that the plugIn DLLs is always registred in sandbox mode. But i am use OnPremise CRM an would like "none" as DLL mode. Can you please test it und change the code from TaskServer.cs "RegisterAssembly" method:
["isolationmode"] = new OptionSetValue(2)
to Code from TaskPlugIn.cs "RegisterAssembly" method:
["isolationmode"] = firstTypeAttribute.IsolationMode == IsolationModeEnum.Sandbox ? new OptionSetValue(2) : new OptionSetValue(1)
??
Thanks :-)

**Comment by phuocle** [comment]
Hi,

I fixed the issue, but cannot release to NuGet with the version **2.13.33**

Please help download the **DynamicsCrm.DevKit.Cli.2.13.33.nupkg.zip** to your local folder and setup Visual Studio that you can update the package from your local folder

**NOTED:** after download the file, please rename it to **DynamicsCrm.DevKit.Cli.2.13.33.nupkg** I do it because this comment cannot allow upload the **.nupkg** file

![image](https://user-images.githubusercontent.com/479729/126416212-62211ab4-b199-494f-a9fd-0ed82fff472c.png)
[DynamicsCrm.DevKit.Cli.2.13.33.nupkg.zip](https://github.com/phuocle/Dynamics-Crm-DevKit/files/6852161/DynamicsCrm.DevKit.Cli.2.13.33.nupkg.zip)

**Comment by AlGu1** [comment]
Wow, great job. Works for me local. We wait for next Nuget Update for all other devoplers in me team ;-)
